-- ── notification_queue ──────────────────────────────────────────────
-- Stores all notifications generated by dbMonitor and other event sources.
-- Flutter polls this table every 5 seconds per device.
CREATE TABLE IF NOT EXISTS notification_queue (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nik VARCHAR(20) NOT NULL,
  event_type VARCHAR(50) NOT NULL COMMENT 'consultation_request, consultation_response, new_admission, sbar_request, emergency_igd_consultation',
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  payload JSON DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_nik_created (nik, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── notification_device_cursor ─────────────────────────────────────
-- Tracks the last notification ID each device has acknowledged.
-- Unique per (nik, device_id) so each device independently tracks cursor.
CREATE TABLE IF NOT EXISTS notification_device_cursor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nik VARCHAR(20) NOT NULL,
  device_id VARCHAR(100) NOT NULL,
  last_read_id BIGINT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_nik_device (nik, device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
